library(tidyverse)
library(readr)
library(SciViews)
library(stats)
library(DescTools)
bd<-read_csv("Byoun original sample period.csv",show_col_types=FALSE)
bd <- bd %>% replace_na(list(oancf=0,y="unknown"))
bd <- bd %>% replace_na(list(recch=0,y="unknown"))
bd <- bd %>% replace_na(list(invch=0,y="unknown"))
bd <- bd %>% replace_na(list(apalch=0,y="unknown"))
bd <- bd %>% replace_na(list(exre=0,y="unknown"))
bd <- bd %>% replace_na(list(dltt=0,y="unknown"))
bd <- bd %>% replace_na(list(dlc=0,y="unknown"))
bd <- bd %>% replace_na(list(capx=0,y='unknown'))
bd <- bd %>% replace_na(list(ivch=0,y='unknown'))
bd <- bd %>% replace_na(list(aqc=0,y='unknown'))
bd <- bd %>% replace_na(list(sppe=0,y='unknown'))
bd <- bd %>% replace_na(list(siv=0,y='unknown'))
bd <- bd %>% replace_na(list(ivstch=0,y='unknown'))
bd <- bd %>% replace_na(list(ivaco=0,y='unknown'))
bd <- bd %>% replace_na(list(aoloch=0,y='unknown'))
bd <- bd %>% replace_na(list(chech=0,y='unknown'))
bd <- bd %>% replace_na(list(fiao=0,y='unknown'))
bd <- bd %>% replace_na(list(dlcch=0,y='unknown'))
bd <- bd %>% replace_na(list(rnd=0,y='unknown'))
bd <- bd %>% replace_na(list(txach=0,y='unknown'))
bd <- bd %>% replace_na(list(oibdp=0,y='unknown'))
bd[10:24] <- bd %>% select(10:24) %>% Winsorize(probs=c(.01,.99999),na.rm=TRUE)
bd$dv <- Winsorize(bd$dv,probs=c(0.0,.9999,na.rm=TRUE))
bd[25:52]<- bd %>% select(25:52) %>% Winsorize(probs=c(.01,.9999),na.rm=TRUE)
bd$xrd <- Winsorize(bd$xrd,probs=c(0.0,.9999,na.rm=TRUE))
bd[53:55] <- bd %>% select(53:55) %>% Winsorize(probs=c(.01,.9999),na.rm=TRUE)
bd03<-filter(bd,fyear==2003)
bd93<-filter(bd,fyear==1993)
bdf <- function(x){
  x<-filter(x,!sich%in%(6000:6799)&!sich%in%(4800:4900)&at>0&sale>0)
  x<-mutate(x,td=dltt+dlc)
  x<-mutate(x,ltd=dltt+dd1)
  x<-mutate(x,mva=at-seq-txditc+(prcc_f*cshpri)-pstkl)
  x<-mutate(x,tdat=td/at)
  x<-mutate(x,ltdat=ltd/at)
  x<-mutate(x,tdmva=td/mva)
  x<-mutate(x,ltdmva=ltd/mva)
  x<-mutate(x,oi=oibdp/at)
  x<-mutate(x,mb=mva/at)
  x<-mutate(x,LnA=ln(at))
  x<-mutate(x,Dep=dp/at)
  x<-mutate(x,fa=ppent/at)
  x<-mutate(x,rnd=xrd/sale)
  x<-mutate(x,divr=dv/at)
  x<-mutate(x,az=(3.3*oibdp+sale+1.4*re+1.2*(lct-act))/at)
  x<-mutate(x,ocf=oancf-recch-invch-apalch-txach+exre)
  x<-mutate(x,i=capx+ivch+aqc-sppe-siv-ivstch-ivaco)
  x<-mutate(x,deltawtd=-recch-invch-apalch-txach-aoloch+chech-fiao)
  x<-mutate(x,deltawltd=-recch-invch-apalch-txach-aoloch+chech-fiao-dlcch)
  x<-mutate(x,deltad=dltis-dltr-dlcch)
  x<-mutate(x,deltae=sstk-prstkc)
  x<-mutate(x,fdtd=divr+i+deltawtd-ocf)
  x<-mutate(x,fdltd=divr+i+deltawltd-ocf)
  x<-mutate(x,fdatd=fdtd/at)
  x<-mutate(x,fdaltd=fdltd/at)
  x<-filter(x,!is.na(tlcf)&!is.na(oi)&!is.na(mb)&!is.na(LnA)&!is.na(Dep)&!is.na(fa)&!is.na(divr)&!is.na(az))
  #x<-filter(x, !is.na(tlcf)&!is.na(dv))
  # print('Count:')
  print(length(x$tic))
  #print(x$fdatd)
  print('Mean')
  print(mean(x$fdatd))
  print(mean(x$fdaltd))
  print('Minimum')
  print(min(x$fdatd),na.rm=TRUE)
  print('Median')
  print(median(x$fdatd),na.rm=TRUE)
  print('Max')
  print(max(x$fdatd),na.rm=TRUE)
  print('SD')
  print(sd(x$fdatd),na.rm=TRUE)
}
bdf(bd)

